# Generated by Django 3.0.8 on 2020-07-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200714_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Transaction_id',
            new_name='transaction_id',
        ),
    ]
